name: flutter_loggy_dio
description: A new Flutter project.
version: 0.1.0
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy:
    path: ../loggy
  dio: ^3.0.10