name: loggy
description: Logger for Dart applications, use mixin for easier separation when needed
version: 1.0.1
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  stack_trace: ^1.9.6

dev_dependencies:
  test: ^1.15.4
