name: flutter_loggy
description: Loggy extension to use 'developer.log' with pretty printer in Flutter
version: 1.0.2
repository: https://github.com/infinum/flutter-logger
homepage: https://github.com/infinum/flutter-logger

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy: ^1.0.0
  rxdart: '>0.1.0 <1.0.0'
