name: flutter_loggy
description: Loggy extensions to use in Flutter
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  loggy:
    path: ../loggy